config/routes.rb
Rails.application.routes.draw do
  
  get 'value_prop/new'

  get 'value_prop/edit'

  get 'value_prop/update'

  get 'comments/new'

  get 'comments/create'

  get 'password_resets/new'

  get 'password_resets/edit'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create' 
  delete 'logout'  => 'sessions#destroy'

  get 'users/new'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  post 'sendcontact'   => 'static_pages#sendcontact'

  get 'signup'=>'users#new'

  get 'register' =>'organisations#new'

  root 'static_pages#home'

  resources:users
  resources:organisations
  resources:tasks
  resources:comments
  resources:value_props
  resources:tasks do
    resources :comments
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :organisations do 
    resources :users 
    resources :tasks
    resource :value_prop
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :organisation
  has_many :comments,dependent: :destroy
  validates :content,presence:true
  validates :user_id,presence:true
  validates :status,
            :presence => { :if => 'status.nil?' }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def index
		@tasks = Task.paginate(page: params[:page])
 	end
 	def show
    	@task = Task.find(params[:id])
      @comments=@task.comments.paginate(page: params[:page])  
  end

  def new
	    @task = Task.new
	    @task.organisation_id =params[:organisation_id]
	    @task.user_id = current_user.id
 	end

 	def create
	    @task = Task.new(task_params)
	    @task.status = 1
	    if @task.save	       	      
	      redirect_to Organisation.find(@task.organisation_id)
	    else
	      render 'new'
	    end
  	end

  def destroy
    myorg = Task.find(params[:id]).organisation_id
    Task.find(params[:id]).destroy
    flash[:success] = "Task deleted"
    redirect_to Organisation.find(myorg)
  end

  	def update
    @task = Task.find(params[:id])
    if @task.update_attributes(task_params)
      # Handle a succes sful update.
      flash[:success] = "task updated"
     # redirect_to @task

    else
    #  render 'edit'
    end
  end

  	private

    def task_params
      params.require(:task).permit(:content, :user_id,:organisation_id,:status)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task.html.erb
    <tr>
     <td><%= task.created_at %></td>
     <td><label><%= link_to task.content[0..50],task %></label></td>
     <td><%= if task.status then "Open" else "Closed" end%></td>
     <td><%= task.user.name %></td>
     <td><%= link_to "", task, method: :delete,
		                                  data: { confirm: "Permanantly remove #{task.content}?"}, class:"fa fa-trash" %></td>
    </tr>

   

app/views/tasks/index.html.erb
<% provide(:title, 'All Tasks') %>
<h1>All tasks</h1>

<%= will_paginate %>

<ul class="users">
  <% @tasks.each do |task| %>
        <%= render task %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/tasks/new.html.erb
<% provide(:title, 'Create Task') %>
<section id="portfolio" class="bg-light-gray organisation">
  <div class="container">
    <div class="row">
            <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Create New Task</h2>
            </div>
        </div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [@task] do |f| %>
      <%= render 'shared/task_error_messages' %>
      <%= f.hidden_field :organisation_id %>
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control' %>

     <%= collection_select(:task, :user_id, User.where(organisation_id:@task.user.organisation_id), :id, :name_display, prompt: true) %>
    <%= f.submit "Create Task", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>
</section>

app/views/tasks/show.html.erb
<% provide(:title, @task.user.name) %>
<section id="portfolio" class="bg-light-gray organisation">
  <div class="container">
    <div class="row">
            <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Task</h2>
                 <!--    <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3> -->
            </div>
        </div>
       <div class="col-lg-12">
          <div class="row">
                <div class="col-lg-8 text-left">
                <p><label>Created On: </label> <%= @task.created_at %></p>
                <p><label>Assigned To: </label> <%= @task.user.name %></p>
                <p><label>Task Content: </label> <%= @task.content %></p>
                <p><%= link_to "Add Comment", new_task_comment_path(@task),class:"page-scroll btn btn-xl"%></p>
                 <%= form_for(@task) do |f| %>
                    <div class="panel-group" id="panel-569650">
                        <div class="panel panel-default">
                        <div class="panel-heading">
                           <a class="panel-title" data-toggle="collapse" data-parent="#panel-569650" href="#panel-element-454753">Manage Task</a>
                        </div>
                        <div id="panel-element-454753" class="panel-collapse collapse">
                            <div class="panel-body">
                           <label>Re-Assign: </label><%= collection_select(:task, :user_id, User.where(organisation_id:@task.user.organisation_id), :id, :name_display, prompt: true) %>
                          <table>
                              <tr>
                                  <td><%= f.label 'status_true', 'Open' %></td>
                                  <td><%= f.radio_button :status, true %></td>
                              </tr>

                              <tr>
                                  <td><%= f.label 'status_false', 'Closed' %></td>
                                  <td><%= f.radio_button :status, false %></td>
                              </tr>
                          </table>
                           <%= f.submit "Update", class: "btn btn-primary" %>
                  <% end %>

                            </div>
                        </div>
                        </div>
                    </div>
                  </div>
                  <div class="col-lg-4 text-right">
                     <% @comments.each do |comment| %>
                            <p><%= render comment %></p>
                  <% end %>  
                  </div>
          </div>
          </div>
  </div>
</section>
 



 