config/routes.rb
Rails.application.routes.draw do
  
  get 'value_prop/new'

  get 'value_prop/edit'

  get 'value_prop/update'

  get 'comments/new'

  get 'comments/create'

  get 'password_resets/new'

  get 'password_resets/edit'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create' 
  delete 'logout'  => 'sessions#destroy'

  get 'users/new'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  post 'sendcontact'   => 'static_pages#sendcontact'

  get 'signup'=>'users#new'

  get 'register' =>'organisations#new'

  root 'static_pages#home'

  resources:users
  resources:organisations
  resources:tasks
  resources:comments
  resources:value_props
  resources:tasks do
    resources :comments
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :organisations do 
    resources :users 
    resources :tasks
    resource :value_prop
  end

end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
	has_many :users,dependent: :destroy
	has_many :tasks,dependent: :destroy
	has_one  :value_prop,dependent: :destroy
	validates :name,presence:true,length:{maximum:240}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email,length:{maximum:240},
	format:{with: VALID_EMAIL_REGEX}
	has_attached_file :logo, 
	:path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
	:url => "/system/:attachment/:id/:basename_:style.:extension",
	:styles => {
	  :thumb    => ['100x100#',  :jpg, :quality => 70],
	  :preview  => ['480x480#',  :jpg, :quality => 70],
	  :large    => ['600>',      :jpg, :quality => 70],
	  :retina   => ['1200>',     :jpg, :quality => 30]
	},
	:convert_options => {
	  :thumb    => '-set colorspace sRGB -strip',
	  :preview  => '-set colorspace sRGB -strip',
	  :large    => '-set colorspace sRGB -strip',
	  :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
	}
	validates_attachment :logo,
	    :presence => true,
	    :size => { :in => 0..10.megabytes },
	    :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }

	 def self.search(search)
        where("name like ?", "%#{search}%") 
  	 end
end
 

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :logged_in_user, only: [:destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

def index
    if params[:q]
      @organisations = Organisation.search(params[:q]).order("created_at DESC").paginate(page: params[:page])
    else
      @organisations = Organisation.paginate(page: params[:page])
    end
     #@organisations = Organisation.paginate.search(params[:search])
 end
 def new
    @organisation = Organisation.new

 end

  def edit
    @organisation = Organisation.find(params[:id])
  end

  def update
    @organisation = Organisation.find(params[:id])
    if @organisation.update_attributes(organisation_params)
      # Handle a succes sful update.
      flash[:success] = "Profile updated"
      redirect_to @organisation

    else
      render 'edit'
    end
  end


 def show
#byebug()
 	@organisation =Organisation.find(params[:id])  
 	@users=@organisation.users.paginate(page: params[:page])
 	@tasks=@organisation.tasks.paginate(page: params[:page])
  @valueprop=@organisation.value_prop
  #byebug()
 	
 end
 def create
 	@organisation = Organisation.new(organisation_params)
 	   if @organisation.save
	      flash[:info] = "Organisation Created."
	      flash[:danger]="Please create a profile for one of your founders."
 		redirect_to new_organisation_user_path(@organisation)
	     # redirect_to @organisation
	    else
	      render 'new'
	    end
 end


#def destroy
 #   Organisation.find(params[:id]).destroy
  #  flash[:success] = "Organisation deleted"
   # redirect_to organisations_url
  #end


 def search
	@organisations = Organisation.paginate.search(params[:search])
 end

# Confirms a logged-in user.
  def logged_in_user
     unless logged_in?
       store_location
       flash[:danger] = "Please log in."
       redirect_to login_url
     end
  end
  # Confirms the correct user.
  def correct_user
      unless (current_user.organisation_id.to_s ==(params[:id]))
        flash[:danger]="You can only edit your own organisation."
        redirect_to(root_url)
      end
      #redirect_to(root_url) unless current_user?(@user)
  end

       # Confirms an admin user.
  def admin_user
      flash[:warning] ="Function can only be performed by admin user"
      redirect_to(root_url) unless current_user.admin?
  end
 
 private

    def organisation_params
      params.require(:organisation).permit(:name, :email, :bpn, :logo)
    end

end

app/helpers/organisations_helper.rb
module OrganisationsHelper
	  
  #Current User belongs to current organisation
  def belongs_to_organisation?
  	if current_user.nil?
  		return false
  	else
		#byebug()
  		!((@organisation.users.find_by id: current_user.id).nil?)
  	end
  end

end

app/views/organisations/_organisation.html.erb
<div class="col-lg-4 col-md-4 col-sm-6 portfolio-item">
                    
                    <div class="portfolio-caption">
                       <!-- <%= gravatar_for organisation, size: 50 %>-->
                        <div><%= image_tag organisation.logo.url(:thumb), class:"gravatar",size:"50" %></div>
                        <br>
                        <div><%= link_to organisation.name, organisation%></p></div>
                      <!--  <%= link_to "", organisation, method: :delete,
		                                  data: { confirm: "Permanantly remove #{organisation.name}?"}, class:"fa fa-trash" %> -->
                    </div> 
 </div>

app/views/organisations/_tasktab.html.erb
<div class="tab-pane active" id="panel-659209">
                <p>
              <% if @organisation.tasks.any? %>
                <table class="table table-hover table-condensed">
                    <thead>
                      <tr>
                        <th>
                          Date Created
                        </th>
                        <th>
                          Task
                        </th>
                        <th>
                          Status
                        </th>
                        <th>
                          Assigned To
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @tasks.each do |task| %>
                                <%= render task %>
                      <% end %>                  
                    </tbody>
                  </table>
                <% end %>
                <%= link_to "Add Task", new_organisation_task_path(@organisation),class:"page-scroll btn btn-xl"%>
                </p>
</div>

app/views/organisations/edit.html.erb
<% provide(:title, "Edit organisation") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@organisation,multipart:true) do |f| %>
      <%= render 'shared/org_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :bpn %>
      <%= f.text_field :bpn, class: 'form-control' %>
      <%= f.file_field :logo, class: 'form-control' %>
     <!-- <%= f.submit "Update my organisation", class: "btn btn-primary" %>-->

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @organisation %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/organisations/index.html.erb
<% provide(:title, 'All Organisations') %>
<section id="portfolio" class="bg-light-gray organisation">
	<div class="container">
		<div class="row">
            <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Our Clients</h2>
                    <!-- <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3> -->
            </div>
        </div>
		<%= will_paginate %>
		<div class="row">
		<ul class="users">
		  <% @organisations.each do |organisation| %>
		        <%= render organisation %>
		  <% end %>
		</ul>
		</div>
		<%= will_paginate %>
	</div>
</section> 

app/views/organisations/new.html.erb
<% provide(:title, 'Create Organisation') %>
<section id="portfolio" class="bg-light-gray organisation">
  <div class="container">
    <div class="row">
            <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Register your Organisation</h2>
                 <!--    <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3> -->
            </div>
        </div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
     <%= form_for (@organisation) do |f| %>
      <%= render 'shared/org_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :bpn %>
      <%= f.text_field :bpn, class: 'form-control' %>
      <%= f.label :logo %>
      <%= f.file_field :logo, class: 'form-control' %>
      <%= f.submit "Create my organisation", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>
</section>

app/views/organisations/show.html.erb
<% provide(:title, @organisation.name) %>
<section class="bg-light-gray organisation">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 text-right">
                      <h4 class="section-heading"> <%= image_tag @organisation.logo.url(:thumb), class:"gravatar",size:"50" %><%= @organisation.name %></h4>
                      <h6 class="section-subheading text-muted">Enterprise in the digital age.</h3> 
      </div>
      <p>
      <!-- <div class="col-xs-3">
      side menu goes here
    </div> -->
    <div class="col-xs-12">

      <div class="tabbable" id="tabs-860189">
        <ul class="nav nav-tabs">
          <li>
            <a href="#panel-609348" class="panel-info" data-toggle="tab"><icon class="fa fa-users"></icon> Our Founders</a>
          </li>  
          <% if logged_in? %>        
              <li class="active">
                <a href="#panel-659209" data-toggle="tab"><icon class="fa fa-wrench"></icon> Our Tasks</a>
              </li>
          <%end%>
          <li >
            <a href="#panel-659206" data-toggle="tab"><icon class="fa fa-trophy"></icon> Our Value Proposition</a>
          </li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane" id="panel-609348">
            <p>
            <% if @organisation.users.any? %>
              <table class="table table-hover table-condensed">
                <thead>
                  <tr>
                  <% if logged_in? %>
                  <th>
                    Organisation
                  </th>
                  <% end %>
                    <th>
                      User
                    </th>
                    <th>
                      Title
                    </th>
                    <th>
                      Email
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <% @users.each do |user| %>
                            <%= render user %>
                  <% end %>                  
                </tbody>
              </table>              
            <% end %>            
            <%= link_to "Add Founder", new_organisation_user_path(@organisation),class:"page-scroll btn btn-xl"%>
            </div>
          <% if logged_in? %> <!--Hide Tasks from non-logged in users-->
              <div class="tab-pane active" id="panel-659209">
                <p>
              <% if @organisation.tasks.any? %>
                <table class="table table-hover table-condensed">
                    <thead>
                      <tr>
                        <th>
                          Date Created
                        </th>
                        <th>
                          Task
                        </th>
                        <th>
                          Status
                        </th>
                        <th>
                          Assigned To
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @tasks.each do |task| %>
                                <%= render task %>
                      <% end %>                  
                    </tbody>
                  </table>
                <% end %>
                <%= link_to "Add Task", new_organisation_task_path(@organisation),class:"page-scroll btn btn-xl"%>
                </p>
              </div>
          <% end %> <!--End hide Tasks-->
          <div class="tab-pane" id="panel-659206">
            <p>
              <% if @organisation.value_prop.nil? %>
                <% if logged_in? && belongs_to_organisation? %>
                  <%= link_to "Value Proposition", new_organisation_value_prop_path(@organisation),class:"page-scroll btn btn-xl"%>
                <% end %>
              <% else%>
              <h2 class="text-muted">Who we are</h2>
              <%= @valueprop.who %>

              <p>
               <h2 class="text-muted">What we do</h2>
              <%= @valueprop.what %>
              <p>
              <h2 class="text-muted">Why we do what we do</h2>
              <%= @valueprop.why %>


              <% end %>
             <!-- Value Prop Section Coming soon-->
            </p>
          </div>
        </div>
      </div>  
    </div>
    </div>       
</div>
</section>






    
    