config/routes.rb
Rails.application.routes.draw do
  
  get 'value_prop/new'

  get 'value_prop/edit'

  get 'value_prop/update'

  get 'comments/new'

  get 'comments/create'

  get 'password_resets/new'

  get 'password_resets/edit'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create' 
  delete 'logout'  => 'sessions#destroy'

  get 'users/new'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  post 'sendcontact'   => 'static_pages#sendcontact'

  get 'signup'=>'users#new'

  get 'register' =>'organisations#new'

  root 'static_pages#home'

  resources:users
  resources:organisations
  resources:tasks
  resources:comments
  resources:value_props
  resources:tasks do
    resources :comments
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :organisations do 
    resources :users 
    resources :tasks
    resource :value_prop
  end

end

app/views/layouts/_about.html.erb
<section id="about" class ="bg-light-gray organisation">
<p>
<p>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">About us</h2>
                    <!-- <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3> -->
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <ul class="timeline">
                        <li>
                            <div class="timeline-image">
                            <%= image_tag("img/about/1.jpg", alt: '', class: "img-circle img-responsive") %>
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                   <!--  <h4>2014-2015</h4> -->
                                    <h4 class="subheading">We Are...</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted">A Zimbabwean Mixed Use Startup & Small Business Incubator | Enterprise Development Leveraging the Internet | Focus : Youth, Especially Young Women!</p>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <%= image_tag("img/about/2.jpg", alt: '', class: "img-circle img-responsive") %>
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <!-- <h4>March 2011</h4> -->
                                    <h4 class="subheading">We are excited by...</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted">Enterprise development in the age of the internet! The possibilities of scale, depth, reach - are endless!</p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="timeline-image">
                               <%= image_tag("img/about/3.jpg", alt: '', class: "img-circle img-responsive") %>
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                   <!--  <h4>December 2012</h4> -->
                                    <h4 class="subheading">Our Goal is to </h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted">Assist you acquire the two things that are the future of small businesses and start-ups : financial literacy and digital skills for small business.</p>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <%= image_tag("img/about/4.jpg", alt: '', class: "img-circle img-responsive") %>
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                   <!--  <h4>July 2014</h4> -->
                                    <h4 class="subheading">We will build...</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted">An ecosystem around you that will nourish and accelerate you to achieving your full potential. We will hold your hand and provide support because successful start-ups are all about community!</p>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <h4>Be Part
                                    <br>Of Our
                                    <br>Story!</h4>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

app/views/layouts/_carousel.html.erb
    <!-- Header -->
<header >
<div class="container-fluid">
<div class="row">
<div class ="col-lg-12 id="carousel-izonehub" class="carousel slide" data-ride="carousel"">


     <!-- <div id="carousel-izonehub" class="carousel slide" data-ride="carousel">-->
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-izonehub" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-izonehub" data-slide-to="1"></li>
          <li data-target="#carousel-izonehub" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">


          <div class="item active">
            <!--<img src="..." alt="...">-->
                <div class="intro-text">
                      <% flash.each do |message_type, message| %>
                      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
                      <% end %>
                      <div class="intro-lead-in">Welcome To Our eHub!</div>
                      <!-- <div class="intro-heading">It's Great To Meet You</div> -->
                      <li><%= link_to "What We Do", root_path(anchor: "services"),class:"page-scroll btn btn-xl"%></li>   
                      <p> 
                      <li><%= link_to "Class '15", register_path ,class:"page-scroll btn btn-xl"%></li>    
                 </div>
                        
          </div>
          <div class="item">
                <div class ="intro-text2">
                <% flash.each do |message_type, message| %>
                      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
                      <% end %>
                      <div class="intro-lead-in"></div>
                      <!-- <div class="intro-heading">It's Great To Meet You</div> -->
                      <li><%= link_to "What We Do", root_path(anchor: "services"),class:"page-scroll btn btn-xl"%></li>   
                      <p> 

                      <li><%= link_to "Class '15", register_path ,class:"page-scroll btn btn-xl"%></li>    
                </div>
          </div>
          <div class="item">
                <div class ="intro-text3">
                <% flash.each do |message_type, message| %>
                      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
                      <% end %>
                      <div class="intro-lead-in"></div>
                      <!-- <div class="intro-heading">It's Great To Meet You</div> -->
                      <li><%= link_to "1776 Challenge Cup Harare '15", "http://www.1776.vc/challenge-cup/apply-to-compete/",class:"page-scroll btn btn-xl",:target=>"_blank"%></li>   
                      <p> 
                      <li><%= link_to "Class '15", register_path ,class:"page-scroll btn btn-xl"%></li>    
                </div>
                </div>
        </div>

        <!-- Controls -->
        <!-- <a class="left carousel-control" href="#carousel-izonehub" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-izonehub" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a> -->
     <!-- </div>-->
</div> <!--Col-lg-->
</div><!--Row-->
</div><!--Container-->
</header>

app/views/layouts/_contact.html.erb
<section id="contact" class ="bg-light-gray organisation">

        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Contact Us</h2>
                    <h3 class="section-subheading text-muted">We'd love to hear from you.</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                <%= form_tag({controller: "static_pages", action: "sendcontact"}, method: "post", id: "contactForm") do %>
                  <!--   <form name="sentMessage" id="contactForm" novalidate action="sendcontact" method ="post"> -->
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                <%= text_field_tag(:name,nil,:class=>"form-control",:placeholder=>"Your Name *",:required=> true) %>
                                    <!-- <input type="text" class="form-control" placeholder="Your Name *" id="name" required data-validation-required-message="Please enter your name.">
 -->                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                        <%= text_field_tag(:email,nil,:type=>"Email",:class=>"form-control",:placeholder=>"Your Email *",:required=> true) %>

                                    <!-- <input type="email" class="form-control" placeholder="Your Email *" id="email" required data-validation-required-message="Please enter your email address.">
                                     --><p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                <%= text_field_tag(:phone,nil,:type=>"text",:class=>"form-control",:placeholder=>"Your Phone *",:required=> true) %>
                                    <!-- <input type="tel" class="form-control" placeholder="Your Phone *" id="phone" required data-validation-required-message="Please enter your phone number."> -->
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                <%= text_area_tag(:message,nil,:type=>"Email",:class=>"form-control",:placeholder=>"Your Message *",:required=> true) %>
                                   <!-- <textarea class="form-control" placeholder="Your Message *" id="message" required data-validation-required-message="Please enter a message."></textarea> -->
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-lg-12 text-center">
                                <div id="success"></div>
                                
                                <button  class="btn btn-xl">Send Message</button>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </section>     

app/views/layouts/_footer.html.erb
<footer class:"navbar-fixed-bottom">
        <!-- <div class="container"> -->
            <div class="row">
                <div class="col-lg-6 col-xs-12 text-left">
                    <span class="copyright">Copyright &copy; <%= link_to "www.izonehub.co.zw", "http://www.izonehub.co.zw" %> 2015</span>
                </div>
                <div class="col-lg-6 col-xs-6 text-left">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                    </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                        <li>
                        <%= link_to "Help", help_path %></li>
                    </ul>
                </div>
            </div>
        <!-- </div> -->
    </footer>

app/views/layouts/_header.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="row">
                <div class="col-lg-2 navbar-header page-scroll">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <%= link_to image_tag('izone-logo.png'), root_path(anchor: "page-top"),class:"navbar-brand page-scroll",id:"logo"%> 
                </div
            <!-- Collect the nav links, forms, and other content for toggling -->
            <!-- <div class="col-lg-10 "> -->
            <div class="col-md-8 col-ms-8 col-xs-8 col-lg-offset-5 col-sm-offset-3 col-md-offset-4 collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <!-- <div class ="row"> -->
               <!--  <div class ="col-lg-3 col-md-6 col-sm-6 col-xs-6" >
                    <%= link_to image_tag('izone-logo.png'), root_path(anchor: "page-top"),class:"navbar-brand page-scroll",id:"logo"%> 
                </div> -->
                
                  <ul class="nav navbar-nav navbar-right">
                      <li class="hidden">
                                  <a href="/"></a>
                              </li>
                               <li>
                                   <%= link_to "About Us", root_path(anchor: "about"),class:"page-scroll"%></li>
                               <li>
                                   <%= link_to "Our Team", root_path(anchor: "team"),class:"page-scroll"%>
                              </li>
                              <li>
                                  <%= link_to "Clients", organisations_path,class:"page-scroll"%>
                              </li>
                              <li>
                               <%= link_to "Services", root_path(anchor: "services"),class:"page-scroll"%>
                               </li>                
                              <% if logged_in? %>
                                      <li class="dropdown">
                                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        Account <b class="caret"></b>
                                      </a>
                                      <ul class="dropdown-menu">
                                      <li><%= link_to "My Organisation", Organisation.find(current_user.organisation_id) %></li>
                                        <li><%= link_to "My Profile", current_user %></li>
                                        <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                                        <li><%= link_to "Edit Organisation", edit_organisation_path(Organisation.find(current_user.organisation_id)) %></li>
                                       
                                         <% if current_user.admin? %>
                                          <li class="divider"></li>
                                             <li><%= link_to "Manage Clients", organisations_path,class:"page-scroll"%></li>
                                             <li><%= link_to "Manage Users", users_path,class:"page-scroll"%></li>
                                             <li class="divider"></li>
                                          <% end %>
                                        
                                        <li>
                                          <%= link_to "Log out", logout_path, method: "delete" %>
                                        </li>
                                      </ul>
                                    </li>
                              <% else %>
                                      <li><%= link_to "Log in", login_path %></li>
                                     
                              <% end %>
                                   <li>
                                   <%= link_to "Contact", root_path(anchor: "contact"),class:"page-scroll"%></li>
                  </ul>
                
            </div>
            <!-- </div> -->
            <!-- /. .row -->
            </div>
             <!-- /.navbar-collapse -->
<!--                 <div class="row">
                    <div class ="col-lg-12" >

                      <div class="row">
                      <span class="pull-right">
                      <div class="col-lg-6 social-links text-center">
                        <ul id ="social-links" class="list-inline social-buttons">
                            <small class ="text-muted">Connect with us:</small>
                            <li><a href="http://www.twitter.com/izonezw"><i class="fa fa-twitter "></i></a>
                            </li>
                            <li><a href="http://www.facebook.com/izonezw"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li><a href="http://www.linkedin.com/izonezw"><i class="fa fa-linkedin"></i></a>
                            </li>
                         </ul>

                          </div>
                     
                          <div class ="col-lg-6">
                          <%= form_tag(organisations_path, :method => "get", class: "navbar-form", id: "search-form") do %>
                           <div class="input-group "> 
                              <%= text_field_tag(:q,nil,class:"form-control text-muted",placeholder:"search") %>
                              <div class="input-group-btn">
                                 <%= button_tag("", class: "btn btn-default") do %><i class="glyphicon glyphicon-search"></i> <% end %>
                              </div>
                          </div>
                    <% end %>
                    </div>
                    </span>
                    </div>
                    
                    </div>
                   </div>    -->                 
                </div>
        </div>
        <!-- /.container-fluid -->
    </nav>

app/views/layouts/_portfolio.html.erb
  <section id="portfolio" class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Portfolio</h2>
                    <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href="#portfolioModal1" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <%= image_tag("img/portfolio/roundicons.png", alt: '', class: "img-responsive") %>     </a>
                    <div class="portfolio-caption">
                        <h4>Round Icons</h4>
                        <p class="text-muted">Graphic Design</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href="#portfolioModal2" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                       <%= image_tag("img/portfolio/startup-framework.png", alt: '', class: "img-responsive") %>
                    </a>
                    <div class="portfolio-caption">
                        <h4>Startup Framework</h4>
                        <p class="text-muted">Website Design</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href="#portfolioModal3" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                     <%= image_tag("img/portfolio/treehouse.png", alt: '', class: "img-responsive") %>
                    </a>
                    <div class="portfolio-caption">
                        <h4>Treehouse</h4>
                        <p class="text-muted">Website Design</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href="#portfolioModal4" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                     <%= image_tag("img/portfolio/golden.png", alt: '', class: "img-responsive") %>
                    </a>
                    <div class="portfolio-caption">
                        <h4>Golden</h4>
                        <p class="text-muted">Website Design</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href="#portfolioModal5" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                       <%= image_tag("img/portfolio/escape.png", alt: '', class: "img-responsive") %>
                    </a>
                    <div class="portfolio-caption">
                        <h4>Escape</h4>
                        <p class="text-muted">Website Design</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href="#portfolioModal6" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                       <%= image_tag("img/portfolio/dreams.png", alt: '', class: "img-responsive") %>
                    </a>
                    <div class="portfolio-caption">
                        <h4>Dreams</h4>
                        <p class="text-muted">Website Design</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

app/views/layouts/_services.html.erb
 <section id="services" class ="bg-light-gray organisation">
 <p>
 <p>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Services</h2>
                    <!-- <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3> -->
                </div>
            </div>
            <div class="row text-center">
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="service-heading">Incubation</h4>
                    <p class="text-muted"> We facilitate the success of start-ups and hatchling companies through training and ecosystem building </p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-laptop fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="service-heading">Acceleration</h4>
                    <p class="text-muted">We help market-tested ideas to grow and achieve scale locally and regionally.</p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="service-heading">Consultancy</h4>
                    <p class="text-muted">We provide consultancy services in financial & Tech literacy for business.</p>
                </div>
            </div>
        </div>
    </section>

app/views/layouts/_shim.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.javascripts/js/1.4.2/respond.min.js"></script>
    <![endif]-->

app/views/layouts/_splash.html.erb
    <!-- Header -->
    <header>
        <div class="container-fluid">
        <div class="row">
        <div class ="col-lg-12">
           <div class="intro-text">
                <% flash.each do |message_type, message| %>
                <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
                <% end %>
                <div class="intro-lead-in">Welcome To Our eHub!</div>
                <div class="intro-heading">It's Great To Meet You</div>
                <li><%= link_to "What We Do", root_path(anchor: "services"),class:"page-scroll btn btn-xl"%></li>   
                <p> 
                <li><%= link_to "Class '15", register_path ,class:"page-scroll btn btn-xl"%></li>    
            </div>
         </div> <!--Col-lg-->
        </div><!--Row-->
        </div><!--Container-->
    </header>

app/views/layouts/_task.html.erb
<li> 
      
	  <p><%= link_to ">>>", "#taskmodal123","data-toggle" => "modal" %></p>
      <p><%=task.content %></p>
      <p class="text-muted"><%=task.user.name%></p>
      <span class="timestamp">
    Posted <%= time_ago_in_words(task.created_at) %> ago.
  </span>
</li>

app/views/layouts/_tasktab.html.erb
<div class="tab-pane active" id="panel-659209">
                <p>
              <% if @organisation.tasks.any? %>
                <table class="table table-hover table-condensed">
                    <thead>
                      <tr>
                        <th>
                          Date Created
                        </th>
                        <th>
                          Task
                        </th>
                        <th>
                          Status
                        </th>
                        <th>
                          Assigned To
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @tasks.each do |task| %>
                                <%= render task %>
                      <% end %>                  
                    </tbody>
                  </table>
                <% end %>
                <%= link_to "Add Task", new_organisation_task_path(@organisation),class:"page-scroll btn btn-xl"%>
                </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title><%= full_title(yield(:title)) %></title>
        <%= stylesheet_link_tag "application", media: "all",
                                               "data-turbolinks-track" => true %>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>
        <%= render 'layouts/shim' %>

        <!-- Bootstrap Core CSS -->
        <link href="css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="css/agency.css" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    </head>
    <body id="page-top" class="index">
        <!-- <div class="container"> -->
        <%= render 'layouts/header' %>
        <%= yield %>
        <%= render 'layouts/footer' %>
        <!-- </div> -->
    </body>
</html>